name: Open and Merge PR

on:
  push:
    branches:
      - main  # Or the default branch for common-workflow

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create PR on gold repo
        id: create-pr
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: 'Hashemjr',
              repo: 'gold',
              title: 'Automated PR',
              body: 'This is an automated PR created by GitHub Actions.',
              base: 'master',
              head: 'new-feature-branch'
            });
            return pullRequest.number;

      - name: Merge PR
        uses: actions/github-script@v6
        with:
          script: |
            const pullNumber = parseInt('${{ steps.create-pr.outputs.result }}', 10);
            await github.rest.pulls.merge({
              owner: 'Hashemjr',
              repo: 'gold',
              pull_number: pullNumber,
              merge_method: 'merge'
            });

