name: Open and Merge PR

on:
  push:
    branches:
      - main  # Or the default branch for common-workflows

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create PR on gold repo
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.APP_TOKEN }}
          repository: Hashemjr/gold
          title: 'Automated PR'
          body: 'This is an automated PR created by GitHub Actions.'
          base: master
          head: new-feature-branch
          commit-message: 'Add new feature branch'

      - name: Merge PR
        uses: peter-evans/merge-pull-request@v4
        with:
          token: ${{ secrets.APP_TOKEN }}
          repository: Hashemjr/gold
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: merge

